steps:
  - label: ":pipeline:" 
    command: whoami
    plugins:
      - kubernetes: 
          containers:
              - name: "container-0"
                image: buildkite/agent:latest 
                securityContext:
                  runAsUser: 30000
                  privileged: false
                  runAsGroup: 30000
                  allowPrivilegeEscalation: false