steps:
  - label: ":pipeline:" 
    command: buildkite-agent pipeline upload .buildkite/pipeline.skipcheckout.yaml
    plugins:
      - kubernetes: 
          podSpec:
            containers:
            - image: buildkite/agent:latest