steps:
  - label: ":pipeline:" 
    command: whoami
    plugins:
      - kubernetes: 
          podSpecPatch: 
            spec:
              securityContext:
                runAsUser: 30000
                runAsGroup: 30000
                fsGroup: 30000
                runAsNonRoot: true
                allowPrivilegeEscalation: false 