steps:
  - label: ":pipeline:" 
    command: whoami && id -g -n
    plugins:
      - kubernetes: 
          podSpecPatch: 
            volumes:
            - name: "dshm"
              emptyDir: {} 
            containers:
            - name: "container-0"
              image: "ghcr.io/siemens/kas/kas:3.3" 
              volumeMounts:
              - name: "dshm"
                mountPath: "/dev/shm"
              # securityContext:
              #   runAsUser: 30000
              #   privileged: false
              #   runAsGroup: 30000
              #   allowPrivilegeEscalation: false