steps:
  - label: ":k8s:"
    command: |-
      while true; do 
          # Your commands here 
          echo "Running..." 
          # Optional: Sleep for a specific duration to prevent high CPU usage 
          sleep 10 
      done 

    plugins:
      - kubernetes:
          checkout:
            skip: true       
          podSpec:
            containers:
            - image: bash:latest    
