steps:
  - label: ":pipeline:" 
    command: whoami 
    plugins:
      - kubernetes: 
          checkout:
            skip: true
          podSpecPatch:  
              containers:
              - name: "container-0"
                image: "alpine:latest" 